---
# -*- coding: utf-8 -*-

language: python
sudo: false
cache: pip
python:
  - "2.7"

install:
  - pip install --upgrade ansible ansible-lint yamllint

before_script:
  - ansible --version
  - ansible-lint --version
  - yamllint --version

script:
  - for dir in *; do
      test -d "$dir" &&
      echo "$dir" &&
      ansible-lint -R -r .testenv/lint-rules/ "$dir";
    done
  - for dir in *; do
      test -d "$dir" &&
      echo "$dir" &&
      yamllint -c ./.testenv/yamllint.yml "$dir";
    done

# vim: set ts=2 sw=2 tw=2 :
