# -*- coding: utf-8 -*-

language: python
sudo: false
cache: pip
python:
  - "2.7"

script:
  - pip install ansible ansible-lint
  - ansible --version
  - ansible-lint --version
  - for dir in *; do test -d "$dir" && ansible-lint "$dir"; done

# vim: set ts=2 sw=2 tw=2 :
