---

- name: enforce root password
  user:
    name: root
    state: present
    password: '{{ users_root_password }}'
    update_password: '{{ users_root_password_update }}'
  tags:
    - role::users
    - role::users:config
  when: users_root_password is defined and users_root_password

- name: create user groups
  group:
    name: '{{ item.group | default(item.name) }}'
    system: '{{ item.system | default(omit) }}'
    gid: '{{ item.gid | default(omit) }}'
    state: '{{ item.state | default("present") }}'
  tags:
    - role::users
    - role::users:config
  with_items: '{{ users_user }}'
  when: item.name is defined and item.name

- name: manage user accounts
  user:
    name: '{{ item.name }}'
    uid: '{{ item.uid | default(omit) }}'
    group: '{{ item.group | default(omit) }}'
    groups: '{{ item.groups | join(",") | default(omit) }}'
    append: '{{ item.append | default(omit) }}'
    comment: '{{ item.comment | default(omit) }}'
    password: '{{ item.password | default("!") }}'
    update_password: '{{ item.update_password | default("on_create") }}'
    system: '{{ item.system | default(omit) }}'
    shell: '{{ item.shell | default(omit) }}'
    home: '{{ item.home | default(omit) }}'
    createhome: '{{ item.createhome | default(omit) }}'
    remove: '{{ item.remove | default(omit) }}'
    state: '{{ item.state | default("present") }}'
  tags:
    - role::users
    - role::users:config
  with_items: '{{ users_user }}'
  when: item.name is defined and item.name

- name: manage ssh keys of users
  authorized_key:
    user: '{{ item.user }}'
    key: '{{ item.key }}'
    exclusive: '{{ item.exclusive | default(omit) }}'
    key_options: '{{ item.options | default(omit) }}'
    manage_dir: '{{ item.manage_dir | default("no") }}'
    path: '{{ item.path | default("/etc/ssh/authorized_keys/" + item.user) }}'
    state: '{{ item.present | default(omit) }}'
  tags:
    - role::users
    - role::users:config
    - role::users:sshkeys
  with_items: '{{ users_ssh_keys }}'
  when: item.user is defined and item.user and
        item.key is defined and item.key
