---

- name: enforce root password
  user:
    name: root
    state: present
    password: '{{ users_root_password }}'
    update_password: '{{ users_root_password_update }}'
  tags:
    - role::users
    - role::users:config
  when: users_root_password is defined and users_root_password

- name: create user groups
  group:
    name: '{{ item.group | default(item.name) }}'
    system: '{{ item.system | default(omit) }}'
    gid: '{{ item.gid | default(omit) }}'
    state: '{{ item.state | default("present") }}'
  tags:
    - role::users
    - role::users:config
  with_items: '{{ users_user }}'
  when: item.name is defined and item.name and
        item.name != 'root'
